export const COMMENT_CREATE_REQUEST='COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS='COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAILURE='COMMENT_CREATE_FAILURE'

export const LIKE_COMMENT_REQUEST='LIKE_COMMENT_REQUEST'
export const LIKE_COMMENT_SUCCESS='LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAILURE='LIKE_COMMENT_FAILURE'

export const FETCH_COMMENTS_REQUEST='FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS='FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE='FETCH_COMMENTS_FAILURE'